Repository JohnnyLAmpAz/smartmag, pull requests merged in 2024-03, with the labels that each got.

#17 UI utente
  proj_eclipse/src/main/java/smartmag/Prova.java
  proj_eclipse/src/main/java/smartmag/models/UtenteModel.java
  proj_eclipse/src/main/java/smartmag/models/ui/UsersTableModel.java
  proj_eclipse/src/main/java/smartmag/ui/UserPanel.java
  proj_eclipse/src/main/java/smartmag/ui/UsersMngmtPanel.java
  proj_eclipse/src/main/java/smartmag/ui/UsersTablePanel.java
  proj_eclipse/src/test/java/smartmag/ProvaTest.java
Labels: ui

#24 UI ordini
  proj_eclipse/src/main/java/smartmag/models/OrderModel.java
  proj_eclipse/src/main/java/smartmag/models/ProductModel.java
  proj_eclipse/src/main/java/smartmag/models/ui/OrderTableModel.java
  proj_eclipse/src/main/java/smartmag/models/ui/ProductOrderTableModel.java
  proj_eclipse/src/main/java/smartmag/ui/OrderDialog.java
  proj_eclipse/src/main/java/smartmag/ui/TabellaOrdini.java
Labels: ui

#18 Modello Movimentazione
  proj_eclipse/src/main/java/smartmag/data/Box.java
  proj_eclipse/src/main/java/smartmag/data/MovimId.java
  proj_eclipse/src/main/java/smartmag/data/Movimentazione.java
  proj_eclipse/src/main/java/smartmag/data/Ordine.java
  proj_eclipse/src/main/java/smartmag/data/StatoMovim.java
  proj_eclipse/src/main/java/smartmag/data/StatoMovimentazione.java
  proj_eclipse/src/main/java/smartmag/data/Utente.java
  proj_eclipse/src/main/java/smartmag/models/BoxModel.java
  proj_eclipse/src/main/java/smartmag/models/MovimenModel.java
  proj_eclipse/src/main/java/smartmag/models/OrderModel.java
  proj_eclipse/src/main/java/smartmag/models/ProductModel.java
  proj_eclipse/src/main/java/smartmag/models/UtenteModel.java
  proj_eclipse/src/main/java/smartmag/models/ui/MovimenTableModel.java
  proj_eclipse/src/main/java/smartmag/ui/AssegnaProdottoDialog.java
  proj_eclipse/src/main/java/smartmag/ui/BoxTableFrame.java
  proj_eclipse/src/main/java/smartmag/ui/MovimTablePanel.java
  proj_eclipse/src/main/java/smartmag/ui/MovimenMngmtPanel.java
  proj_eclipse/src/main/java/smartmag/ui/ProdottiTableFrame.java
  proj_eclipse/src/main/java/smartmag/utils/PrintUtils.java
  proj_eclipse/src/main/java/smartmag/utils/Tupla.java
Labels: models

#37 Testing - struttura di base
  proj_eclipse/db/config/drop_tables.sql
  proj_eclipse/src/main/java/smartmag/db/Db.java
  proj_eclipse/src/main/java/smartmag/db/utils/CodeGenJOOQ.java
  proj_eclipse/src/main/java/smartmag/models/BaseModel.java
  proj_eclipse/src/main/java/smartmag/models/UtenteModel.java
  proj_eclipse/src/test/java/smartmag/BaseTest.java
  proj_eclipse/src/test/java/smartmag/data/BoxTest.java
  proj_eclipse/src/test/java/smartmag/data/ProdottoTest.java
  proj_eclipse/src/test/java/smartmag/models/UtenteModelTest.java
Labels: db, testing

#33 22 esecuzione applicazione e gestione finestre
  proj_eclipse/db/config/db_creation.sql
  proj_eclipse/src/main/java/smartmag/Prova.java
  proj_eclipse/src/main/java/smartmag/models/BoxModel.java
  proj_eclipse/src/main/java/smartmag/models/MovimenModel.java
  proj_eclipse/src/main/java/smartmag/models/OrderModel.java
  proj_eclipse/src/main/java/smartmag/models/ui/BoxTableModel.java
  proj_eclipse/src/main/java/smartmag/models/ui/OrderTableModel.java
  proj_eclipse/src/main/java/smartmag/ui/AssegnaProdottoDialog.java
  proj_eclipse/src/main/java/smartmag/ui/BoxTableFrame.java
  proj_eclipse/src/main/java/smartmag/ui/LoginDialog.java
  proj_eclipse/src/main/java/smartmag/ui/MainWindow.java
  proj_eclipse/src/main/java/smartmag/ui/MovimenMngmtPanel.java
  proj_eclipse/src/main/java/smartmag/ui/OrderDialog.java
  proj_eclipse/src/main/java/smartmag/ui/ProdottiTableFrame.java
  proj_eclipse/src/main/java/smartmag/ui/TabellaOrdini.java
Labels: ui

#40 Docs davide to main
  docs/ConfigurationManagement.md
  docs/PeopleManagement.md
  docs/RequirementEngineering.md
  docs/SoftwareDesign.md
  docs/SoftwareLifeCycle.md
  docs/SoftwareQuality.md
Labels: documentation

#47 Testing Prodotto
  proj_eclipse/src/main/java/smartmag/models/ProductModel.java
  proj_eclipse/src/main/java/smartmag/ui/ProdottiTableFrame.java
  proj_eclipse/src/test/java/smartmag/models/ProductModelTest.java
Labels: testing

#46 Testing Movimentazioni
  proj_eclipse/src/main/java/smartmag/models/BoxModel.java
  proj_eclipse/src/main/java/smartmag/models/MovimenModel.java
  proj_eclipse/src/main/java/smartmag/models/OrderModel.java
  proj_eclipse/src/test/java/smartmag/models/MovimenModelTest.java
Labels: models, testing

#48 Merge test Davide nel main
  proj_eclipse/src/main/java/smartmag/models/OrderModel.java
  proj_eclipse/src/test/java/smartmag/models/OrderModelTest.java
Labels: testing

#49 Testing Box
  proj_eclipse/src/main/java/smartmag/models/BoxModel.java
  proj_eclipse/src/main/java/smartmag/models/ProductModel.java
  proj_eclipse/src/test/java/smartmag/models/BoxModelTest.java
Labels: testing
